The Children of the Snakes
--------------------------

Basilisks vs Dragons
-Basilisks are Universal Truths, Dragons are Universal Forces.

Basilisks have Gaze attacks that do not do energy damage. High cost, and the damage effects are always 1. Examples: Gaze Fear, Gaze 1, Gaze Sleep, Gaze Agony, Gaze Stun. They also have touch poison effects.

Dragons have Blast attacks that always do either typed energy, Knockback or Fear. The damage is graduated, and can get very high. Examples: Blast Fire 4, Blast Knockback 6 meters.

The Birds
---------

The birds are messengers. Genus and species are associated with kind and faction.

Eg Corvidae: Jackdaws, Crows, Ravens, Rooks, Magpies.

Doves.

Pelicans.

The Beasts
----------

Rage, frenzy, self polymorph, regeneration, some minor infection powers, some minor resilience powers.

Other Legendary Creatures
-------------------------

Gryphons vs Manticores.
- Pride.

Unicorns vs Kelpies vs Satyrs vs Horse Liches.
- Unicorns as Purity vs Innocence.
- Kelpies as ?
- Satyrs as ?
- Horse Liches as ?

Hydras.

Trolls.

The Gentry.

Firebird vs Thunderbird.
- Both embody Rebirth.

The Undead
----------

Vampires:
- Many kinds of vampires.
- Mental effects. Mostly point effects. Lots of Charm and Dominate. Touch Paralyse, Touch Drain, Ghoul Fever Disease cards.

Liches

Shadows

Shades

Ghouls

Ghasts

Zombies

Demons
------

Demons are any creature native to a Hell metaplane. They come in various kinds.

Equippable 'esoteric language like' things:
-------------------------------------------

Sigils, runes, ideograms, cards (like Tarot). Not just one language of each kind, but several.

Common themes and images - eg large bodies of water are protective, dissipative or imprisoning, fire is cleansing, illuminating, or scourging.
Also themes like the birds, and some specific potent individuals eg Gods and legendary heroes.

On the Nature of Mana
---------------------

On the Nature of Metaplanes
---------------------------

Sources, Sinks, Floating Mana Level, Forced Mana Level, Charge, Current, Ground, Static, Resonance and the Universal Circuit.

Types of Realms
---------------

Hell Realms


Fae Realms
- All Fae realms use the card travel system

On the Nature of Manabridges
----------------------------

On the nature of death and resurrection
---------------------------------------

Many ressurrections spells and methods.

The most common is a thirteen part spell, which requires 13 expert mages with ritual ability, and thirteen expert ritual spells, which all use a 3rd level reagent each, and must all be performed together simultaneously at a place of power.

Elemental damage types:
-----------------------

Flame, Shock, Silver, Iron, Spirit, Holy, Arcane?


Sections
--------

A brief description of the metasetting, the setting, and the metagame.

'The kinds of things a hero can be'

The call, effect, and state of being system.
List of calls, list of states of being, examples of interactions between calls, examples of effects.
How to run a scene with calls.
How this interacts with fluff and calibration.
How this differs between tabletop and larp.

XP - The normal ability trees. Rule/fluff dichotomy.
GP - 'Knowledges' - Spells, potions, schematics, creature lores, languages
SP - Money. Stuff. Artifacts.
BP - Backgrounds. Connections, title, otherwise unrepresented fields of knowledge and experience, occupations, tragedies that befell you, blessings or curses, fame or infamy. Anything where you say to a GM 'I know this/can do this because of my backstory'.

Introduce the idea of the Shadowguide. Introduce the idea of Snowflake Points.

Calibration. Getting everyone on the same page. GM and player. Players. GMs.

Calculating and using 'aptitude points' and 'chronicle success points'.
Challenges. Descriptions.

The downtime system overview.
Personal downtime metasystem, plus some examples of specific downtime systems for specific types of games.
Factional or group downtime metasystems, plus some examples of specific downtime systems for specific types of games.
XP, GP, SP and BP awarded during downtime.
Generated fiction.
